# Generated by Django 4.2.5 on 2023-09-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0034_alter_hotellocation_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("broadcast_on", models.DateTimeField()),
                ("sent", models.BooleanField(default=False)),
                (
                    "request_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.request",
                    ),
                ),
            ],
            options={
                "ordering": ["-broadcast_on"],
            },
        ),
    ]
