# Generated by Django 4.2.5 on 2023-09-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_rename_request_id_broadcastnotification_request"),
    ]

    operations = [
        migrations.RenameField(
            model_name="broadcastnotification",
            old_name="request",
            new_name="request_for",
        ),
    ]
